name: Java CI with Gradle

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Set up JDK
        uses: actions/setup-java@v4.7.0
        with:
          distribution: adopt
          java-version: 17
      - name: Build LimboAuth
        run: ./gradlew build
      - name: Release the build
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/libs/*.jar
          body: ${{ join(github.event.commits.*.message, '\n') }}
          prerelease: true
          name: Dev-build ${{ steps.git-version.outputs.id }}
          tag: dev-build
